// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4843.404bot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController liftSystemLift;
    public static SpeedController driveTrainRightDrive;
    public static SpeedController driveTrainLeftDrive;
    public static RobotDrive driveTrainRobotDrive21;
    public static SpeedController shootShoot;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        liftSystemLift = new Jaguar(1, 3);
	LiveWindow.addActuator("Lift System", "Lift", (Jaguar) liftSystemLift);
        
        driveTrainRightDrive = new Victor(1, 1);
	LiveWindow.addActuator("Drive Train", "Right Drive", (Victor) driveTrainRightDrive);
        
        driveTrainLeftDrive = new Victor(1, 2);
	LiveWindow.addActuator("Drive Train", "Left Drive", (Victor) driveTrainLeftDrive);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainLeftDrive, driveTrainRightDrive);
	
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);
        driveTrainRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);        
        shootShoot = new Jaguar(1, 4);
	LiveWindow.addActuator("Shoot", "Shoot", (Jaguar) shootShoot);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
