// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc4843.404bot.subsystems;

import org.usfirst.frc4843.404bot.RobotMap;
import org.usfirst.frc4843.404bot.commands.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Lift extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
     subsystems = RobotMap.subsystems;
    Joystick joystick1 = RobotMap.joystick1;
    JoystickButton liftButton = RobotMap.liftButton;
    Joystick joystick2 = RobotMap.joystick2;
     operatorInterface = RobotMap.operatorInterface;
     autonomousCommand = RobotMap.autonomousCommand;
     drive = RobotMap.drive;
     commands = RobotMap.commands;
     404bot = RobotMap.404bot;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ${name.replace(' ', '')}());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

