// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc4843.Robot;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc4843.Robot.commands.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    
  //public Joystick joystick2;
    public Joystick joystick1;      //XBOX CONTROLLER
    public JoystickButton spinupButton;
    public JoystickButton lightsButton;
    public JoystickButton lightsButton2;
    public JoystickButton loadButton;
    public JoystickButton loadReverseButton;
    public JoystickButton fireButton;
    public JoystickButton extendButton;
    public JoystickButton retractButton; 
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
       //joystick2 = new Joystick(2);
        //This is the OI setup for use with the HID compliant xbox 360 controller
        joystick1 = new Joystick(1);
        lightsButton = new JoystickButton(joystick1, 4);      
        lightsButton2= new JoystickButton(joystick1, 2);
        loadReverseButton = new JoystickButton(joystick1, 3);
        loadButton = new JoystickButton(joystick1, 1);
        fireButton = new JoystickButton(joystick1,5);
        extendButton=new JoystickButton(joystick1,7);
        retractButton=new JoystickButton(joystick1,8);
        spinupButton = new JoystickButton(joystick1, 6);
        fireButton.whileHeld(new FireCommand());
        fireButton.whenReleased(new FireResetCommand());
        spinupButton.whileHeld(new SpinUpCommand());
        spinupButton.whenReleased(new SpinUpStopCommand());
        extendButton.whenPressed(new ExtendCommand());
        retractButton.whenPressed(new RetractCommand());
        loadButton.whileHeld(new LoadCommand());
        loadButton.whenReleased(new LoadStopCommand());
        loadReverseButton.whileHeld(new LoadReverseCommand());
        loadReverseButton.whenReleased(new LoadStopCommand());
        lightsButton.whileHeld(new Lights1Command());
        lightsButton.whenReleased(new Lights2Command());
        lightsButton2.whileHeld(new LightsOffCommand());
        lightsButton2.whenReleased(new LightsOffCommand());
        //liftButton.whileHeld(new LiftCommand());
        //liftButton.whenReleased(new StopCommand());
        //lowerButton.whileHeld(new LowerCommand());
        //lowerButton.whenReleased(new StopCommand());
        
        
        

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("DriveCommand", new DriveCommand());

        SmartDashboard.putData("ShootCommand", new ShootCommand());

        SmartDashboard.putData("LiftCommand", new Lights1Command());
        
        SmartDashboard.putData("LoadCommand", new LoadCommand());

        SmartDashboard.putData("FireCommand", new FireCommand());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }
    
  //public Joystick getJoystick2() {
  //   return joystick2;
  //}
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    
    }


