
package org.usfirst.frc4843.Robot.subsystems;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc4843.Robot.RobotMap;

public class MagExtension extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Servo MagExtension = RobotMap.MagExtension;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

     public void Extend(){
         
       MagExtension.setAngle(115);
     }
     
     public void Retract(){
    
         MagExtension.setAngle(0);    
     }

     public double Angle(){
        return MagExtension.getAngle();
     }
    public void initDefaultCommand() {
    }
}


